# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'activity_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1350, 771)
        MainWindow.setStyleSheet("background-color: rgb(47, 47, 47);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setEnabled(False)
        self.widget.setGeometry(QtCore.QRect(280, 20, 801, 641))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 40, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(4, 192, 157);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 90, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(4, 192, 157);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(4, 192, 157);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 190, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(4, 192, 157);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(50, 240, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(4, 192, 157);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 290, 80, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(4, 192, 157);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(160, 40, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(160, 90, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(160, 140, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(160, 190, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(160, 240, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(160, 290, 250, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_12.setObjectName("label_12")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(20, 70, 220, 3))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.progressBar.setFont(font)
        self.progressBar.setStyleSheet("QProgressBar{\n"
"    border-color: transparent;\n"
"    \n"
"    color: transparent;\n"
"}\n"
"QProgressBar::chunk  {\n"
"    background-color: rgb(4, 192, 157);\n"
"}")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setTextVisible(True)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setGeometry(QtCore.QRect(20, 40, 21, 20))
        self.radioButton.setTabletTracking(False)
        self.radioButton.setAcceptDrops(False)
        self.radioButton.setAutoFillBackground(False)
        self.radioButton.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton.setText("")
        self.radioButton.setCheckable(True)
        self.radioButton.setChecked(False)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(20, 90, 21, 20))
        self.radioButton_2.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_2.setText("")
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(20, 140, 21, 20))
        self.radioButton_3.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_3.setText("")
        self.radioButton_3.setAutoExclusive(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(20, 190, 21, 20))
        self.radioButton_4.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_4.setText("")
        self.radioButton_4.setAutoExclusive(False)
        self.radioButton_4.setObjectName("radioButton_4")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(20, 240, 21, 20))
        self.radioButton_5.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_5.setText("")
        self.radioButton_5.setAutoExclusive(False)
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(20, 290, 21, 20))
        self.radioButton_6.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_6.setText("")
        self.radioButton_6.setAutoExclusive(False)
        self.radioButton_6.setObjectName("radioButton_6")
        self.progressBar_2 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_2.setGeometry(QtCore.QRect(20, 120, 220, 3))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.progressBar_2.setFont(font)
        self.progressBar_2.setStyleSheet("QProgressBar{\n"
"    border-color: transparent;\n"
"    \n"
"    color: transparent;\n"
"}\n"
"QProgressBar::chunk  {\n"
"    background-color: rgb(4, 192, 157);\n"
"}")
        self.progressBar_2.setProperty("value", 100)
        self.progressBar_2.setObjectName("progressBar_2")
        self.progressBar_3 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_3.setGeometry(QtCore.QRect(20, 170, 220, 3))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.progressBar_3.setFont(font)
        self.progressBar_3.setStyleSheet("QProgressBar{\n"
"    border-color: transparent;\n"
"    \n"
"    color: transparent;\n"
"}\n"
"QProgressBar::chunk  {\n"
"    background-color: rgb(4, 192, 157);\n"
"}")
        self.progressBar_3.setProperty("value", 100)
        self.progressBar_3.setObjectName("progressBar_3")
        self.progressBar_4 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_4.setGeometry(QtCore.QRect(20, 220, 220, 3))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.progressBar_4.setFont(font)
        self.progressBar_4.setStyleSheet("QProgressBar{\n"
"    border-color: transparent;\n"
"    \n"
"    color: transparent;\n"
"}\n"
"QProgressBar::chunk  {\n"
"    background-color: rgb(4, 192, 157);\n"
"}")
        self.progressBar_4.setProperty("value", 100)
        self.progressBar_4.setObjectName("progressBar_4")
        self.progressBar_5 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_5.setGeometry(QtCore.QRect(20, 270, 220, 3))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.progressBar_5.setFont(font)
        self.progressBar_5.setStyleSheet("QProgressBar{\n"
"    border-color: transparent;\n"
"    \n"
"    color: transparent;\n"
"}\n"
"QProgressBar::chunk  {\n"
"    background-color: rgb(4, 192, 157);\n"
"}")
        self.progressBar_5.setProperty("value", 100)
        self.progressBar_5.setObjectName("progressBar_5")
        self.progressBar_6 = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar_6.setGeometry(QtCore.QRect(20, 320, 220, 3))
        font = QtGui.QFont()
        font.setPointSize(5)
        self.progressBar_6.setFont(font)
        self.progressBar_6.setStyleSheet("QProgressBar{\n"
"    border-color: transparent;\n"
"    \n"
"    color: transparent;\n"
"}\n"
"QProgressBar::chunk  {\n"
"    background-color: rgb(4, 192, 157);\n"
"}")
        self.progressBar_6.setProperty("value", 100)
        self.progressBar_6.setObjectName("progressBar_6")
        self.radioButton_8 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_8.setGeometry(QtCore.QRect(600, 710, 81, 20))
        self.radioButton_8.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_8.setAutoExclusive(False)
        self.radioButton_8.setObjectName("radioButton_8")
        self.radioButton_10 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_10.setGeometry(QtCore.QRect(700, 710, 111, 20))
        self.radioButton_10.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_10.setAutoExclusive(False)
        self.radioButton_10.setObjectName("radioButton_10")
        self.radioButton_7 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_7.setGeometry(QtCore.QRect(600, 680, 81, 20))
        self.radioButton_7.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_7.setAutoExclusive(False)
        self.radioButton_7.setObjectName("radioButton_7")
        self.radioButton_9 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_9.setGeometry(QtCore.QRect(700, 680, 81, 20))
        self.radioButton_9.setStyleSheet("QRadioButton {\n"
"    color:rgb(147, 147, 147);\n"
"}\n"
"\n"
"QRadioButton::indicator:checked {\n"
"    border: 2px solid rgb(4, 192, 157);\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"QRadioButton::indicator {\n"
"    border: 2px solid rgb(147, 147, 147);\n"
"    border-radius: 8px;\n"
"}\n"
"")
        self.radioButton_9.setAutoExclusive(False)
        self.radioButton_9.setObjectName("radioButton_9")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "TextLabel"))
        self.label_6.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "TextLabel"))
        self.label_8.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "TextLabel"))
        self.label_10.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "TextLabel"))
        self.label_12.setText(_translate("MainWindow", "TextLabel"))
        self.radioButton_8.setText(_translate("MainWindow", "Легенда"))
        self.radioButton_10.setText(_translate("MainWindow", "Общее время"))
        self.radioButton_7.setText(_translate("MainWindow", "Проценты"))
        self.radioButton_9.setText(_translate("MainWindow", "Подписи"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
